// GENERATED by app/tools/gen_brand.py from @tenor/brand tokens.js.
// Do NOT edit by hand - brand values have a single source of truth.
import SwiftUI

enum TenorColor {
    static let ink = Color(hex: 0x000000)
    static let graphite = Color(hex: 0x1A1A1A)
    static let steel = Color(hex: 0x3D3D3D)
    static let concrete = Color(hex: 0x8A8A86)
    static let bone = Color(hex: 0xF0EFEA)
    static let paper = Color(hex: 0xFAFAF7)
    static let pure = Color(hex: 0xFFFFFF)
    static let signal = Color(hex: 0x0066FF)
}

enum TenorOpacity {
    static let namespace: Double = 0.5
    static let syntax: Double = 0.3
    static let focal: Double = 1.0
}

enum TenorRadius {
    static let hero: CGFloat = 0
    static let sm: CGFloat = 4
    static let md: CGFloat = 8
    static let lg: CGFloat = 12
}
