#!/usr/bin/env python3
"""Generate TenorBrand.generated.swift from the @tenor/brand JS tokens.

Single source of truth = the brand package; we never hand-type brand hex /
opacity / radius in Swift (brand-lint rule: no hardcoded brand data). Re-run
after the brand package changes:  python3 app/tools/gen_brand.py
"""
import re
import pathlib

HERE = pathlib.Path(__file__).resolve()
SRC = pathlib.Path("/Users/tuan/Claude/Tenor/Tenor Branding/packages/brand/src/tokens.js")
OUT = HERE.parent.parent / "Sources" / "Brand" / "TenorBrand.generated.swift"

tokens = SRC.read_text()


def block(name):
    m = re.search(name + r"\s*=\s*Object\.freeze\(\{(.*?)\}\)", tokens, re.S)
    if not m:
        raise SystemExit("token block not found: " + name)
    return m.group(1)


colors = re.findall(r"(\w+):\s*'(#[0-9A-Fa-f]{6})'", block("TENOR_COLOR"))
opacity = re.findall(r"(\w+):\s*([0-9.]+)", block("TENOR_OPACITY"))
radius = re.findall(r"(\w+):\s*(\d+)", block("TENOR_RADIUS"))

if not (colors and opacity and radius):
    raise SystemExit("parse failed: colors=%d opacity=%d radius=%d"
                     % (len(colors), len(opacity), len(radius)))

out = ["// GENERATED by app/tools/gen_brand.py from @tenor/brand tokens.js.",
       "// Do NOT edit by hand - brand values have a single source of truth.",
       "import SwiftUI", "", "enum TenorColor {"]
for name, hexv in colors:
    out.append("    static let %s = Color(hex: 0x%s)" % (name, hexv[1:]))
out += ["}", "", "enum TenorOpacity {"]
for name, val in opacity:
    out.append("    static let %s: Double = %s" % (name, val))
out += ["}", "", "enum TenorRadius {"]
for name, val in radius:
    out.append("    static let %s: CGFloat = %s" % (name, val))
out += ["}", ""]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out))
print("wrote", OUT, "(%d colors, %d opacity, %d radius)" % (len(colors), len(opacity), len(radius)))
